# Generated by Django 4.2.2 on 2023-07-24 04:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, null=True)),
                ('last_name', models.CharField(max_length=150, null=True)),
                ('email_address', models.CharField(max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('phone_no', models.CharField(max_length=255, null=True)),
                ('country', models.CharField(max_length=50, null=True)),
                ('state', models.CharField(max_length=50, null=True)),
                ('city', models.CharField(max_length=50, null=True)),
                ('zip_code', models.CharField(max_length=50, null=True)),
                ('address_one', models.TextField(max_length=500, null=True)),
                ('address_two', models.TextField(max_length=500, null=True)),
                ('order_description', models.TextField(max_length=500, null=True)),
                ('is_card_payment', models.BooleanField(default=True)),
                ('card_holder_name', models.CharField(max_length=100, null=True)),
                ('card_number', models.CharField(max_length=100, null=True)),
                ('cvc', models.CharField(max_length=6, null=True)),
                ('exp_date', models.CharField(max_length=10, null=True)),
                ('status', models.CharField(choices=[('1', 'In Progress'), ('2', 'Shipped')], default='1', max_length=10)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
