# Generated by Django 4.2.2 on 2023-07-24 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='order_total',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
    ]
