# Generated by Django 4.2.2 on 2023-07-24 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orders_order_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='address_two',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
