# Generated by Django 4.2.2 on 2023-07-24 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_orders_address_two'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='card_holder_name',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='card_number',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='cvc',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='exp_date',
        ),
    ]
