# Generated by Django 4.2.2 on 2023-06-27 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discounted_price',
        ),
        migrations.AddField(
            model_name='product',
            name='discounted_percent',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
