# Generated by Django 4.2.2 on 2023-06-27 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_description_product_long_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_at_discount',
            field=models.BooleanField(default=False),
        ),
    ]
