# Generated by Django 4.2.2 on 2023-06-27 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_is_at_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimages',
            name='is_thumbnail',
            field=models.BooleanField(default=False),
        ),
    ]
